image: guergeiro/pnpm:16

stages:
  - build
  - deploy

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

before_script:
  - pnpm config set store-dir .pnpm-store

build-release:
  stage: build
  only:
    - tags
  except:
    - branches
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
  script:
    - pnpm install --loglevel=error
    - pnpm ngcc # Run npm-script ngcc, if ng build does it, the ci breaks (not enough memory)
    - pnpm build:prod
    - cd dist/
    - ls -al

build-testing:
  stage: build
  only:
    - develop
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
  script:
    - pnpm install --loglevel=error
    - pnpm ngcc # Run npm-script ngcc, if ng build does it, the ci breaks (not enough memory)
    - pnpm build:testing
    - cd dist/
    - ls -al

build-dev:
  stage: build
  only:
    - branches
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
  script:
    - npm install --force  --loglevel=error --no-progress
    - pnpm ngcc # Run npm-script ngcc, if ng build does it, the ci breaks (not enough memory)
    - pnpm build:dev
    - cd dist/
    - ls -al

deploy-release:
  stage: deploy
  needs: ['build-release']
  dependencies:
    - build-release
  only:
    - tags
  except:
    - branches
  cache: {}
  script:
    - apt-get update -qq && apt-get install -y -qq zip openssh-client >> /dev/null
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - version=$(git describe --tags $(git rev-list --tags --max-count=1))
    - cd dist/
    - zip -r "WaiterRobot-Web-${version}.zip" ./WaiterRobot-Web >> /dev/null
    - cp "WaiterRobot-Web-${version}.zip" WaiterRobot-Web-latest.zip
    - scp -P $SSH_PORT -o StrictHostKeyChecking=no -o LogLevel=ERROR ./WaiterRobot-Web-latest.zip $SSH_USERNAME@$SSH_HOST:/var/www/datepoll-share/WaiterRobot/Web-Releases/ > /dev/null
    - scp -P $SSH_PORT -o StrictHostKeyChecking=no -o LogLevel=ERROR "WaiterRobot-Web-${version}.zip" $SSH_USERNAME@$SSH_HOST:/var/www/datepoll-share/WaiterRobot/Web-Releases/ > /dev/null

deploy-dev:
  stage: deploy
  needs: ['build-dev']
  dependencies:
    - build-dev
  only:
    - develop
  cache: {}
  script:
    - apt-get update -qq && apt-get install -y -qq zip openssh-client >> /dev/null
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - cd dist/
    - zip -r WaiterRobot-Web-dev.zip ./WaiterRobot-Web >> /dev/null
    - scp -P $SSH_PORT -o StrictHostKeyChecking=no -o LogLevel=ERROR ./WaiterRobot-Web-dev.zip $SSH_USERNAME@$SSH_HOST:/var/www/datepoll-share/WaiterRobot/Web-Releases/ > /dev/null

deploy-testing:
  tags:
    - kaupis
  stage: deploy
  needs: ['build-testing']
  dependencies:
    - build-testing
  only:
    - develop
  cache: {}
  script:
    - apt-get update -qq && apt-get install -y -qq zip openssh-client >> /dev/null
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - echo "$SSH_DEMO_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - cd dist/
    - zip -r WaiterRobot-Web-testing.zip ./WaiterRobot-Web >> /dev/null
    - scp -P $SSH_PORT -o StrictHostKeyChecking=no -o LogLevel=ERROR ./WaiterRobot-Web-testing.zip $SSH_USERNAME@$SSH_HOST:/var/www/datepoll-share/WaiterRobot/Web-Releases/ > /dev/null
    - ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR $SSH_DEMO_USERNAME@$SSH_DEMO_HOST -p $SSH_DEMO_PORT "cd /opt/waiterrobot-web && ./frontend.sh -v dev -f" >> /dev/null
