name: Build lava

on:
  push:
    tags:
      - "*.*.*-lava-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Version
        # VERSION 3.4.0-lava-12345 -> 3.4.0-lava
        run: echo "VERSION=${${{ github.ref_name }}%-*}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker lava-local image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          target: local
          build-args: |
            version=${{ github.ref_name }}
          # tags: 3.4.0-lava-12345_local, 3.4.0-lava_local, latest-lava_local
          tags: |
            ghcr.io/datepollsystems/waiterrobot-web:${{ github.ref_name }}_local
            ghcr.io/datepollsystems/waiterrobot-web:${{ steps.version.outputs.VERSION }}_local
            ghcr.io/datepollsystems/waiterrobot-web:latest-lava_local

      - name: Build and push Docker lava-lava image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          target: lava
          build-args: |
            version=${{ github.ref_name }}
          # tags: 3.4.0-lava-12345_lava, 3.4.0-lava_lava, latest-lava_lava
          tags: |
            ghcr.io/datepollsystems/waiterrobot-web:${{ github.ref_name }}_lava
            ghcr.io/datepollsystems/waiterrobot-web:${{ steps.main-version.outputs.MAIN_VERSION }}_lava
            ghcr.io/datepollsystems/waiterrobot-web:latest-lava_lava
