name: Build license report
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 */30 * *' # At 04:00 on every 30ts day-of-month.
jobs:
  build:
    name: build license report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: setup node and pnpm
        uses: dafnik/setup-node-pnpm@v1
        with:
          install: true

      - name: generate new report
        run: |
          pnpm exec license-report --only=prod --output=json > ./src/assets/licenses_new.json --fields=name --fields=licenseType --fields=link --fields=installedVersion --fields=author
          pnpm exec prettier --write ./src/assets/licenses.json

      - uses: LouisBrunner/diff-action@v0.2.0
        id: diff-check
        with:
          old: ./src/assets/licenses.json
          new: ./src/assets/licenses_new.json
          mode: addition
          tolerance: same

      - name: Move files in place if needed
        if: steps.diff-check.outputs.passed == 'false'
        run: |
          rm -f ./src/assets/licenses.json
          mv ./src/assets/licenses_new.json ./src/assets/licenses.json

      - name: Create New Pull Request If Needed
        if: steps.diff-check.outputs.passed == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          title: Generated new licenses report
          delete-branch: true
          branch-suffix: timestamp
          commit-message: Generated new license json
          body: ${{ steps.diff-check.outputs.output }}
