name: Build prod

on:
  push:
    tags:
      - '*.*.*'
      - '!*.*.*-lava-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker local image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          target: local
          build-args: |
            version=${{ github.ref_name }}
          # tags: 3.4.0_local, latest_local
          tags: |
            ghcr.io/datepollsystems/waiterrobot-web:${{ github.ref_name }}_local
            ghcr.io/datepollsystems/waiterrobot-web:latest_local

      - name: Build and push Docker lava image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          target: lava
          build-args: |
            version=${{ github.ref_name }}
          # tags: 3.4.0_lava, latest_lava
          tags: |
            ghcr.io/datepollsystems/waiterrobot-web:${{ github.ref_name }}_lava
            ghcr.io/datepollsystems/waiterrobot-web:latest_lava

      - name: Build and push Docker prod image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          target: prod
          build-args: |
            version=${{ github.ref_name }}
          # tags: 3.4.0, latest
          tags: |
            ghcr.io/datepollsystems/waiterrobot-web:${{ github.ref_name }}
            ghcr.io/datepollsystems/waiterrobot-web:latest
